import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/components/layout/AppSidebar";
import { cn } from "@/lib/utils";
import { TasksProvider } from "./context/taskContext";
import { AuthProvider } from "./context/authContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("text-xl", "h-full", "antialiased", "font-sans")}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          
          <TasksProvider>
            <SidebarProvider
              style={
                {
                  "--sidebar-width": "14rem",
                  "--sidebar-width-mobile": "18rem",
                } as React.CSSProperties
              }
            >
              <AppSidebar />
              <main className="w-full flex">
                <SidebarTrigger />
                <div className="p-5 grow">{children}</div>
              </main>
            </SidebarProvider>
          </TasksProvider>
     
        </AuthProvider>
      </body>
    </html>
  );
}
