import type { Metadata } from "next";
import { Cabin, Ubuntu, Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/Sidebar";
import Header from "@/app/components/Header";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const CabinFont = Cabin({
  subsets: ["latin"],
});
const UbuntuBlack = Ubuntu({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("text-xl", "h-full", "antialiased", CabinFont.className, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <div style={{ display: "flex", height: "100vh" }}>
          <Sidebar />
          <div style={{ flex: 1, display: "flex", flexDirection: "column" }}>
            <Header />
            <main style={{ padding: 16, flex: 1, overflow: "auto" }}>
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
